apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-boot-apps
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  project: argo-apps
  source:
    repoURL: https://github.com/j-kinyanjui/minikube-argocd-traefik-example.git
    path: charts/spring-boot-apps
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
